#!/bin/sh
 
CPS_DRIVER_MANUFACTURE_ID=0024
 
CPS_SPIDIO_VERSION=$(/sbin/modinfo ./cpsdio_spi.ko | grep version: | awk 'NR == 1{ print $2 }')
 
echo "-------- Driver Manufacture ID ------------------"
echo "Manufacture ID : $CPS_DRIVER_MANUFACTURE_ID "
echo "-------- CPS-MC341 driver ---------------------"
echo "DIO driver (cpsdio_spi) : "$CPS_SPIDIO_VERSION
echo "------------------------------------------------"
