#!/bin/sh

create_mcs341_driver_check(){
MANUFACTURE_ID=$1

echo "#!/bin/sh" > driver_version_check
echo " " >> driver_version_check
echo "CPS_DRIVER_MANUFACTURE_ID=$MANUFACTURE_ID" >> driver_version_check
echo " " >> driver_version_check
echo "CPS_DRIVER_VERSION=\$(/sbin/modinfo ./cps-driver.ko | grep version:| awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo "CPS_DIO_VERSION=\$(/sbin/modinfo ./cpsdio.ko | grep version: | awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo "CPS_AIO_VERSION=\$(/sbin/modinfo ./cpsaio.ko | grep version:| awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo "CPS_COM_VERSION=\$(/sbin/modinfo ./8250_cpscom.ko | grep version: | awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo "CPS_SSI_VERSION=\$(/sbin/modinfo ./cpsssi.ko | grep version: | awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo "CPS_CNT_VERSION=\$(/sbin/modinfo ./cpscnt.ko | grep version: | awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo " " >> driver_version_check
echo "echo \"-------- Driver Manufacture ID ------------------\"" >> driver_version_check
echo "echo \"Manufacture ID : \$CPS_DRIVER_MANUFACTURE_ID \"" >> driver_version_check
echo "echo \"-------- CPS-MCS341 driver ---------------------\"" >> driver_version_check
echo "echo \"base driver (cps-driver) : \" \$CPS_DRIVER_VERSION" >> driver_version_check
echo "echo \"COM driver (8250_cpscom) : \" \$CPS_COM_VERSION" >> driver_version_check
echo "echo \"DIO driver (cpsdio) : \" \$CPS_DIO_VERSION" >> driver_version_check
echo "echo \"AIO driver (cpsaio) : \" \$CPS_AIO_VERSION" >> driver_version_check
echo "echo \"SSI driver (cpsssi) : \" \$CPS_SSI_VERSION" >> driver_version_check
echo "echo \"CNT driver (cpscnt) : \" \$CPS_CNT_VERSION" >> driver_version_check
echo "echo \"------------------------------------------------\"" >> driver_version_check

chmod 755 driver_version_check
}

create_mc341_driver_check(){
MANUFACTURE_ID=$1

echo "#!/bin/sh" > driver_version_check
echo " " >> driver_version_check
echo "CPS_DRIVER_MANUFACTURE_ID=$MANUFACTURE_ID" >> driver_version_check
echo " " >> driver_version_check
echo "CPS_SPIDIO_VERSION=\$(/sbin/modinfo ./cpsdio_spi.ko | grep version: | awk 'NR == 1{ print \$2 }')" >> driver_version_check
echo " " >> driver_version_check
echo "echo \"-------- Driver Manufacture ID ------------------\"" >> driver_version_check
echo "echo \"Manufacture ID : \$CPS_DRIVER_MANUFACTURE_ID \"" >> driver_version_check
echo "echo \"-------- CPS-MC341 driver ---------------------\"" >> driver_version_check
echo "echo \"DIO driver (cpsdio_spi) : \"\$CPS_SPIDIO_VERSION" >> driver_version_check
echo "echo \"------------------------------------------------\"" >> driver_version_check

chmod 755 driver_version_check
}


cd mcs341
create_mcs341_driver_check "0024"
./driver_version_check

cd ../mc341
create_mc341_driver_check "0024"
./driver_version_check

cd ../

