#!/bin/sh
 
CPS_DRIVER_MANUFACTURE_ID=0024
 
CPS_DRIVER_VERSION=$(/sbin/modinfo ./cps-driver.ko | grep version:| awk 'NR == 1{ print $2 }')
CPS_DIO_VERSION=$(/sbin/modinfo ./cpsdio.ko | grep version: | awk 'NR == 1{ print $2 }')
CPS_AIO_VERSION=$(/sbin/modinfo ./cpsaio.ko | grep version:| awk 'NR == 1{ print $2 }')
CPS_COM_VERSION=$(/sbin/modinfo ./8250_cpscom.ko | grep version: | awk 'NR == 1{ print $2 }')
CPS_SSI_VERSION=$(/sbin/modinfo ./cpsssi.ko | grep version: | awk 'NR == 1{ print $2 }')
CPS_CNT_VERSION=$(/sbin/modinfo ./cpscnt.ko | grep version: | awk 'NR == 1{ print $2 }')
 
echo "-------- Driver Manufacture ID ------------------"
echo "Manufacture ID : $CPS_DRIVER_MANUFACTURE_ID "
echo "-------- CPS-MCS341 driver ---------------------"
echo "base driver (cps-driver) : " $CPS_DRIVER_VERSION
echo "COM driver (8250_cpscom) : " $CPS_COM_VERSION
echo "DIO driver (cpsdio) : " $CPS_DIO_VERSION
echo "AIO driver (cpsaio) : " $CPS_AIO_VERSION
echo "SSI driver (cpsssi) : " $CPS_SSI_VERSION
echo "CNT driver (cpscnt) : " $CPS_CNT_VERSION
echo "------------------------------------------------"
