/*** cps_common_devdata.h ******************************/



/* CPS-AI-1608LI and CPS-AO-1604LI */
#define	OFFSET_AIDATA_CPS_AIO	0x0
#define	OFFSET_AISTATUS_CPS_AIO	0x4
#define	OFFSET_AODATA_CPS_AIO 0x8
#define	OFFSET_AOSTATUS_CPS_AIO	0xC
#define	OFFSET_MEMSTATUS_CPS_AIO	0x1C
#define	OFFSET_EXT_COMMAND_LOWER_CPS_AIO 0x20
#define	OFFSET_EXT_COMMAND_UPPER_CPS_AIO 0x22
#define	OFFSET_EXT_DATA_LOWER_CPS_AIO 0x24
#define	OFFSET_EXT_DATA_UPPER_CPS_AIO 0x26
#define	OFFSET_ECUCHECK_CPS_AIO	0x28
#define	OFFSET_INTERRUPT_LOWER_CPS_AIO	0x2C
#define	OFFSET_INTERRUPT_UPPER_CPS_AIO	0x2E
#define	OFFSET_ECU_COMMAND_LOWER_CPS_AIO	0x28
#define	OFFSET_ECU_COMMAND_UPPER_CPS_AIO	0x2A
#define	OFFSET_ECU_DATA_LOWER_CPS_AIO 0x2C
#define	OFFSET_ECU_DATA_UPPER_CPS_AIO 0x2E

/* MEM STATUS */
#define CPU_AIO_MEMSTATUS_DRE	0x0001
#define CPU_AIO_MEMSTATUS_MDRE	0x0002
#define CPU_AIO_MEMSTATUS_DWE	0x0100
#define CPU_AIO_MEMSTATUS_MDWE	0x0200

/*************************************************************************************************************/
/* CPS-AIO Extension */
#define CPS_AIO_ADDRESS_MODE_ECU	0x01
#define CPS_AIO_ADDRESS_MODE_COMMAND	0x00

/* CPS-AIO ECU / Command */
#define CPS_AIO_COMMAND_BASE_ECU		0x0000
#define CPS_AIO_COMMAND_BASE_AI			0x1000
#define CPS_AIO_COMMAND_BASE_AO			0x2000
//#define CPS_AIO_COMMAND_BASE_DI			0x3000
//#define CPS_AIO_COMMAND_BASE_DO			0x4000
//#define CPS_AIO_COMMAND_BASE_CNT		0x5000
#define CPS_AIO_COMMAND_BASE_MEM		0x6000
#define CPS_AIO_COMMAND_MASK	0xF000
/* CPS-AIO Command Read or Write */
#define CPS_AIO_COMMAND_CALL 0x00
#define CPS_AIO_COMMAND_READ	0x01
#define CPS_AIO_COMMAND_WRITE 0x02

/* CPS-AIO ECU */
#define CPS_AIO_COMMAND_ECU_INIT	( CPS_AIO_COMMAND_BASE_ECU | 0x00 )
#define CPS_AIO_COMMAND_ECU_SETIRQMASK_ENABLE	( CPS_AIO_COMMAND_BASE_ECU | 0x01 )
#define CPS_AIO_COMMAND_ECU_SETIRQMASK_DISABLE	( CPS_AIO_COMMAND_BASE_ECU | 0x02 )
#define CPS_AIO_COMMAND_ECU_SETINPUTSIGNAL	( CPS_AIO_COMMAND_BASE_ECU | 0x03 )
#define CPS_AIO_COMMAND_ECU_GENERAL_PULSE_COM0	( CPS_AIO_COMMAND_BASE_ECU | 0x05 )
#define CPS_AIO_COMMAND_ECU_AI_UNUSUAL_STOP	( CPS_AIO_COMMAND_BASE_ECU | 0x10 )
#define CPS_AIO_COMMAND_ECU_AO_UNUSUAL_STOP	( CPS_AIO_COMMAND_BASE_ECU | 0x11 )
#define CPS_AIO_COMMAND_ECU_AI_INTERRUPT_FLAG	( CPS_AIO_COMMAND_BASE_AI | 0x00 )
#define CPS_AIO_COMMAND_ECU_AO_INTERRUPT_FLAG	( CPS_AIO_COMMAND_BASE_AO | 0x00 )

/* CPS-AIO AI Command */
#define CPS_AIO_COMMAND_AI_INIT ( CPS_AIO_COMMAND_BASE_AI | 0x00 )
#define CPS_AIO_COMMAND_AI_GATE_OPEN	( CPS_AIO_COMMAND_BASE_AI | 0x01 )
#define CPS_AIO_COMMAND_AI_FORCE_STOP	( CPS_AIO_COMMAND_BASE_AI | 0x02 )
#define CPS_AIO_COMMAND_AI_SET_INTERNAL_CLOCK	( CPS_AIO_COMMAND_BASE_AI | 0x03 )
#define CPS_AIO_COMMAND_AI_SET_CHANNELS ( CPS_AIO_COMMAND_BASE_AI | 0x05 )
#define CPS_AIO_COMMAND_AI_SET_BEFORE_TRIGGER_SAMPLING_NUMBER	( CPS_AIO_COMMAND_BASE_AI | 0x09 )
#define CPS_AIO_COMMAND_AI_SET_EXCHANGE	( CPS_AIO_COMMAND_BASE_AI | 0x0C )
#define CPS_AIO_COMMAND_AI_SET_CALIBRATION_TERMS	( CPS_AIO_COMMAND_BASE_AI | 0x20 )
#define CPS_AIO_COMMAND_AI_SET_CALIBRATION_EEPROM	( CPS_AIO_COMMAND_BASE_AI | 0x21 )

/* CPS-AIO AO Command */
#define CPS_AIO_COMMAND_AO_INIT ( CPS_AIO_COMMAND_BASE_AO | 0x00 )
#define CPS_AIO_COMMAND_AO_GATE_OPEN	( CPS_AIO_COMMAND_BASE_AO | 0x01 )
#define CPS_AIO_COMMAND_AO_FORCE_STOP	( CPS_AIO_COMMAND_BASE_AO | 0x02 )
#define CPS_AIO_COMMAND_AO_SET_INTERNAL_CLOCK	( CPS_AIO_COMMAND_BASE_AO | 0x03 )
#define CPS_AIO_COMMAND_AO_SET_CHANNELS ( CPS_AIO_COMMAND_BASE_AO | 0x05 )
#define CPS_AIO_COMMAND_AO_SET_BEFORE_TRIGGER_SAMPLING_NUMBER	( CPS_AIO_COMMAND_BASE_AO | 0x09 )
#define CPS_AIO_COMMAND_AO_SET_EXCHANGE	( CPS_AIO_COMMAND_BASE_AO | 0x0C )
#define CPS_AIO_COMMAND_AO_SET_CALIBRATION_TERMS	( CPS_AIO_COMMAND_BASE_AO | 0x20 )
#define CPS_AIO_COMMAND_AO_SET_CALIBRATION_EEPROM	( CPS_AIO_COMMAND_BASE_AO | 0x21 )

/* CPS-AIO MEM Command */
#define CPS_AIO_COMMAND_MEM_INIT ( CPS_AIO_COMMAND_BASE_MEM | 0x00 )
#define CPS_AIO_COMMAND_MEM_AI_CLEAR	( CPS_AIO_COMMAND_BASE_MEM | 0x07 )
#define CPS_AIO_COMMAND_MEM_AO_CLEAR	( CPS_AIO_COMMAND_BASE_MEM | 0x08 )
#define CPS_AIO_COMMAND_MEM_AI_FIFO_COUNTER	( CPS_AIO_COMMAND_BASE_MEM | 0x0B )
#define CPS_AIO_COMMAND_MEM_AO_FIFO_COUNTER ( CPS_AIO_COMMAND_BASE_MEM | 0x0C )
#define CPS_AIO_COMMAND_MEM_SET_AI_COMPARE_TYPE	( CPS_AIO_COMMAND_BASE_MEM | 0x10 )
#define CPS_AIO_COMMAND_MEM_SET_AI_COMPARE_DATA	( CPS_AIO_COMMAND_BASE_MEM | 0x11 )
#define CPS_AIO_COMMAND_MEM_SET_AO_COMPARE_TYPE	( CPS_AIO_COMMAND_BASE_MEM | 0x20 )
#define CPS_AIO_COMMAND_MEM_SET_AO_COMPARE_DATA	( CPS_AIO_COMMAND_BASE_MEM | 0x21 )

/*************************************************************************************************************/
/* CPS-AIO ECU SET INPUT SIGNAL VALUES (SET_INP_SIG) */
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AI_PARMIT_TRG	0x0000
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AI_NOTPARMIT_TRG	0x0002
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AI_SAMP_CLK	0x0004
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AO_UPD_PARMIT_TRG	0x0020
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AO_UPD_NOTPARMIT_TRG	0x0022
#define CPS_AIO_ECU_SET_INP_SIG_DIST_AO_UPD_CLK	0x0024

#define CPS_AIO_ECU_SET_INP_SIG_SRC_NON_CONNECT		0x0000
#define CPS_AIO_ECU_SET_INP_SIG_SRC_AI_INTERNAL_CLK	0x0004 /* AI INTERNAL CLOCK */ 
#define CPS_AIO_ECU_SET_INP_SIG_SRC_AI_BEFTRG_NUMEND	0x0011 /* AI BEFORE TRIGGER NUM END */ 
#define CPS_AIO_ECU_SET_INP_SIG_SRC_AO_INTERNAL_CLK	0x0042 /* AO INTERNAL CLOCK */ 
#define CPS_AIO_ECU_SET_INP_SIG_SRC_AO_BEFTRG_NUMEND	0x0050 /* AO BEFORE TRIGGER NUM END */ 
#define CPS_AIO_ECU_SET_INP_SIG_SRC_MEM_AODATA_EMPTY	0x0160 /* MEM AO Data Empty */ 
#define CPS_AIO_ECU_SET_INP_SIG_SRC_ECU_GENERAL_COM0	0x0180	/* General command 0 */

/* CPS-AIO ECU AI UNUSUAL STOP VALUES (AI_UNU_STP) */
#define CPS_AIO_ECU_AI_UNU_STP_AI_CLK_ERR	0x0001	/* AI CLOCK ERROR */
#define CPS_AIO_ECU_AI_UNU_STP_AI_OVERFLOW	0x0100	/* AI OVER FLOW */

/* CPS-AIO ECU AO UNUSUAL STOP VALUES (AO_UNU_STP) */
#define CPS_AIO_ECU_AO_UNU_STP_AO_CLK_ERR	0x0001	/* AO CLOCK ERROR */
#define CPS_AIO_ECU_AO_UNU_STP_AO_EMPTY	0x0100	/* AO EMPTY */
#define CPS_AIO_ECU_AO_UNU_STP_AO_EXT_STP	0x1000	/* AO EXTERNAL STOP */

/* CPS-AIO AI SET EXCHANGE VALUES (SET_EXC) */
#define CPS_AIO_AI_SET_EXC_ENABLE_SINGLE	0x0000
#define CPS_AIO_AI_SET_EXC_ENABLE_MULTI	0x0001

/* CPS-AIO AI SET CALIBRATION TERMS VALUES (SET_CAL_TRM ) */
#define CPS_AIO_AI_SET_CAL_TRM_SELECT_OFFSET	0x0000
#define CPS_AIO_AI_SET_CAL_TRM_SELECT_GAIN	0x0001
#define CPS_AIO_AI_SET_CAL_TRM_RANGE_PM10V	0x0000

/* CPS-AIO AO SET EXCHANGE VALUES (SET_EXC) */
#define CPS_AIO_AO_SET_EXC_ENABLE_SINGLE	0x0000
#define CPS_AIO_AO_SET_EXC_ENABLE_MULTI	0x0001

/* CPS-AIO AO SET CALIBRATION TERMS VALUES ( SET_CAL_TRM ) */
#define CPS_AIO_AO_SET_CAL_TRM_SELECT_OFFSET	0x0000
#define CPS_AIO_AO_SET_CAL_TRM_SELECT_GAIN	0x0001
#define CPS_AIO_AO_SET_CAL_TRM_RANGE_PM10V	0x0000

/**************************************************/
